name: Auto Reels Creator
on:
  schedule:
    - cron: '0 0 * * *' # 매일 한국 시간 오전 9시 실행
  workflow_dispatch: # 직접 실행 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install System Libs
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick ffmpeg
          # 자막 생성을 위한 보안 정책 해제
          sudo sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml

      - name: Install Python Libs
        run: pip install -r requirements.txt

      - name: Run Main Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py

      - name: Save Video
        uses: actions/upload-artifact@v3
        with:
          name: daily-reels-video
          path: final_reels.mp4
