name: Auto Reels Creator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 3.9에서 3.10으로 업그레이드

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          python -m pip install --upgrade pip
          pip install google-generativeai moviepy==1.0.3 Pillow

      - name: Configure ImageMagick
        run: |
          sudo sed -i 's/policy domain="path" rights="none" pattern="@\*"/policy domain="path" rights="read|write" pattern="@\*"/g' /etc/ImageMagick-6/policy.xml

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: daily-reels-video
          path: final_reels.mp4
